### ISSUE TITLE
ValueError: mathutils.Euler(): invalid euler order 'XYZ'

### ISSUE THREAD

**Issue by moderator0527** [catta202000/CMRNet#22]
Hello, @cattaneod ,

I have a problem with evaluation process, while using your KITTI datasets.
I prepared every requirements and conditions, but the same error message keeps appearing like this:

`
with test_sequence=00 maps_folder=local_maps data_folder=./KITTI_ODOMETRY/sequen                                                                                                                       ces/ weight="['./iter1.tar', './iter2.tar', './iter3.tar']"
WARNING - CMRNet-evaluate-iterative - No observers have been added to this run
INFO - CMRNet-evaluate-iterative - Running command 'main'
INFO - CMRNet-evaluate-iterative - Started
TEST SET - Not found: ./KITTI_ODOMETRY/sequences/test_RT_seq00_10.00_2.00.csv
Generating a new one
1506
  0%|                                                  | 0/1506 [00:00<?, ?it/s]                                                                                                                              Init worker 0 with seed 398646958
Init worker 1 with seed 398646959
Init worker 2 with seed 398646960
Init worker 3 with seed 398646961
Init worker 4 with seed 398646962
Init worker 5 with seed 398646963
ERROR - CMRNet-evaluate-iterative - Failed after 0:04:37!
Traceback (most recent calls WITHOUT Sacred internals):
  File "evaluate_iterative_single_CALIB.py", line 184, in main
    for batch_idx, sample in enumerate(tqdm(TestImgLoader)):
  File "/home/ius/.local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 897, i                                                                                                                              n __iter__
    for obj in iterable:
  File "/home/ius/.local/lib/python3.6/site-packages/torch/utils/data/dataloader                                                                                                                              .py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/ius/.local/lib/python3.6/site-packages/torch/utils/data/dataloader                                                                                                                              .py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/home/ius/.local/lib/python3.6/site-packages/torch/utils/data/dataloader                                                                                                                              .py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/ius/.local/lib/python3.6/site-packages/torch/utils/data/dataloader                                                                                                                              .py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/ius/바탕화면/CMRNet/DatasetVisibilityKitti.py", line 196, in __get                                                                                                                              item__
    R = mathutils.Euler((rotx, roty, rotz), 'XYZ')
ValueError: mathutils.Euler(): invalid euler order 'XYZ'
`

![image](https://user-images.githubusercontent.com/44308210/212528307-91e52b31-bac5-4f52-bc17-7b21084393c0.png)

Could you please help me with this?

Thanks for your great work and support!

**Comment by cattaneod** [comment]
Hello @moderator0527,

how did you install mathutils? please remember that you should install it from https://gitlab.com/m1lhaus/blender-mathutils with the command
`pip install git+https://gitlab.com/m1lhaus/blender-mathutils.git`

**Comment by Huleyun** [comment]
@moderator0527  try to delete the 'XYZ', like this:
> mathutils.Euler((rotx, roty, rotz))

this problem may be caused by the version difference of mathutils
